display_name: Invaders
icon: assets/logo.png
summary:  Space Invaders Game App for the Linux machines!
group: Games
vendor: REChain Network Solutions
packager: Sorokin Dmitry Olegovich
packagerEmail: dmitry.justdev@gmail.com
license: MIT
url: https://github.com/Katya-AI-Systems-LLC/SpaceInv

#build_arch: aarch64

requires:
  - mpv
  - libjsoncpp-dev
  - libsecret-1-dev
  - libsecret-1-0
  - librhash0
  - libwebkit2gtk-4.0-dev
  - libolm3

keywords:
  - Space
  - Invaders

generic_name: Space Invaders Game App for the Linux!

categories:
  - Games

startup_notify: true
