display_name: Invaders
package_name: spaceinvaders
maintainer:
  name: Sorokin Dmitry Olegovich
  email: dmitry.justdev@gmail.com
priority: optional
section: x11
installed_size: 660400
essential: false
icon: assets/logo.png

postinstall_scripts:
  - echo "Installed my awesome Space Invaders Game!"
postuninstall_scripts:
  - echo "Surprised Pickachu face with Invaders Game!"

keywords:
  - Space
  - Invaders
  - Game
  - Linux

generic_name: Space Invaders Game Application

categories:
  - Games

startup_notify: true

# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml
